"""
Load initial weights from binary files generated by C++ program
"""
import struct
import numpy as np

def load_matrix(filename):
    """Load a matrix from binary file"""
    with open(filename, 'rb') as f:
        # Read dimensions (uint32_t)
        rows = struct.unpack('I', f.read(4))[0]
        cols = struct.unpack('I', f.read(4))[0]
        
        # Read data
        data = f.read(rows * cols * 4)  # 4 bytes per float
        matrix = np.frombuffer(data, dtype=np.float32).reshape(rows, cols)
        
        return matrix

def load_vector(filename):
    """Load a vector from binary file"""
    with open(filename, 'rb') as f:
        # Read size (uint32_t)
        size = struct.unpack('I', f.read(4))[0]
        
        # Read data
        data = f.read(size * 4)  # 4 bytes per float
        vector = np.frombuffer(data, dtype=np.float32)
        
        return vector

def load_initial_weights(prefix="initial_weights"):
    """
    Load all initial weights from binary files
    
    Returns:
        tuple: (w1, w2, b1, b2) as numpy arrays
    """
    w1 = load_matrix(f"{prefix}_W1.bin")
    w2 = load_matrix(f"{prefix}_W2.bin")
    b1 = load_vector(f"{prefix}_b1.bin")
    b2 = load_vector(f"{prefix}_b2.bin")
    
    return w1, w2, b1, b2
